branch-defaults:
  master:
    environment: MyFirstElasticBeanstalkApplication-dev
environment-defaults:
  MyFirstElasticBeanstalkApplication-dev:
    branch: master
    repository: inspectorgoldfinch
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: inspectorgoldfinch
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-west-2
  profile: null
  sc: git
